### ISSUE TITLE
photos can not be regenerated

### ISSUE THREAD

**Issue by ptrongithub** [Piwigo/Piwigo#1003]
Getting error `# photos can not be regenerated` in Batch -> Generate Multiple Batch Size Images. Image sizes not being generated on upload.
From the php_errors.log file:
```
[13-Apr-2019 18:48:48 America/New_York] PHP Fatal error:  Uncaught exception 'ImagickException' with message 'unable to open image `././upload/2019/04/13/20190413172232-f087ab9d.jpg': No such file or directory @ error/blob.c/OpenBlob/2702' in ...\piwigo\admin\include\image.class.php:415
Stack trace:
#0 ...\piwigo\admin\include\image.class.php(415): Imagick->__construct('././upload/2...')
#1 ...\piwigo\admin\include\image.class.php(87): image_imagick->__construct('././upload/2...')
#2 ...\piwigo\i.php(524): pwg_image->__construct('././upload/2...')
#3 {main}
  thrown in ...\piwigo\admin\include\image.class.php on line 415

```

**Comment by StevenPolley** [comment]
Yapakipe, I believe this is a different issue than the one you're referring to.  The error message is showing the file on the local filesystem doesn't exist, so it may have at one point and been imported to piwigo and exists in the database, but the local file is missing.
