### ISSUE TITLE
Check for php-mbstring before installing

### ISSUE THREAD

**Issue by tvwerkhoven** [Piwigo/Piwigo#1280]
It appears piwigo requires php-mbstring but doesn't check this. When installing piwigo the installer stops (shows a blank screen) and my nginx error log shows the below error. Perhaps add a library check?
```
2021/01/14 21:48:33 [error] 4068718#4068718: *1701 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function mb_convert_encoding() in /var/www/html/photos/include/emogrifier.class.php:434
Stack trace:
#0 /var/www/html/photos/include/emogrifier.class.php(411): Emogrifier->getUnifiedHtml()
#1 /var/www/html/photos/include/emogrifier.class.php(233): Emogrifier->createXmlDocument()
#2 /var/www/html/photos/include/functions_mail.inc.php(955): Emogrifier->emogrify()
#3 /var/www/html/photos/include/functions_mail.inc.php(853): move_css_to_body()
#4 /var/www/html/photos/install.php(524): pwg_mail()
#5 {main}
  thrown in /var/www/html/photos/include/emogrifier.class.php on line 434" while reading response header from upstream, client: redacted.invalid, server: redacted.invalid, request: "POST /photos/install.php?language=en_GB HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php-fpm.sock:", host: "redacted.invalid", referrer: "https://redacted.invalid/photos/install.php"
```

**Comment by Matt-PMCT** [comment]
Just a note that I came to report exactly this. Would be super helpful if it checked and let me know, but the installer just goes to a blank screen.
