### ISSUE TITLE
Error accessing the server

### ISSUE THREAD

**Issue by angel6700** [Piwigo/Piwigo#1439]
Hello,

I have been using piwigo for a long time installed in my own raspberry pi home server.
Recently I'm getting this error when accessing it:

```
Deprecated: Invalid characters passed for attempted conversion, these have been ignored in /usr/share/webapps/piwigo/include/template.class.php on line 215

Deprecated: Invalid characters passed for attempted conversion, these have been ignored in /usr/share/webapps/piwigo/include/template.class.php on line 1024
/* Thumbnail "elastic" layout */ .thumbnails { margin: 1em 0; padding: 0; list-style: none; text-align: center; /* to center the whole collection in .content */ } .thumbnails LI { display: inline } .thumbnails .wrap1 { margin: 0 7px 5px 7px; display: table-cell; display: inline-table; display: inline-block;/* Why 3 display option ??? */ vertical-align: top; /* OK with Opera and IE6 not Geko */ text-align: center; /* to center the thumbnail and legend in Geko/Opera */ } .thumbnails .wrap2 { margin: 0; /* important reset the margins */ display: table-cell;/* block prevents vertical-align here */ vertical-align: middle;/* Ok with Opera and Geko not IE6 */ border-radius: 4px; /* round corners with CSS3 compliant browsers */ border: 1px solid gray; } .thumbnails .wrap2 A { display: block; } .thumbnails IMG { vertical-align: middle; } .thumbnails .thumbLegend { overflow: hidden;/* oversized legend is clipped */ height: 4em; /* legend height (don't set auto to be Gecko friendly)*/ }
Fatal error: Uncaught Error: Undefined constant "MODUS_POP" in /usr/share/webapps/piwigo/_data/templates_c/ehk1dl^33cbd7b4ce204d3721f4e69415f71aee89e547bb_0.file.index.css.tpl.php:60 Stack trace: #0 /usr/share/webapps/piwigo/_data/templates_c/ehk1dl^33cbd7b4ce204d3721f4e69415f71aee89e547bb_0.file.index.css.tpl.php(60): constant('MODUS_POP')
#1 /usr/share/webapps/piwigo/include/smarty/libs/sysplugins/smarty_template_resource_base.php(122): content_60aa8ccb120d88_40778765(Object(Smarty_Internal_Template))
#2 /usr/share/webapps/piwigo/include/smarty/libs/sysplugins/smarty_template_compiled.php(199): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#3 /usr/share/webapps/piwigo/include/smarty/libs/sysplugins/smarty_internal_template.php(159): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#4 /usr/share/webapps/piwigo/include/smarty/libs/sysplugins/smarty_internal_templatebase.php(191): Smarty_Internal_Template->render(false, 0)
#5 /usr/share/webapps/piwigo/include/smarty/libs/sysplugins/smarty_internal_templatebase.php(94): Smarty_Internal_TemplateBase->_execute(Object(Smarty_Internal_Template), NULL, NULL, NULL, 0)
#6 /usr/share/webapps/piwigo/include/template.class.php(469): Smarty_Internal_TemplateBase->fetch('/usr/share/weba...')
#7 /usr/share/webapps/piwigo/include/template.class.php(1961): Template->parse('css.969b4de18fc...', true)
#8 /usr/share/webapps/piwigo/include/template.class.php(1907): FileCombiner->process_combinable(Object(Css), true, false, '')
#9 /usr/share/webapps/piwigo/include/template.class.php(1882): FileCombiner->flush_pending(Array, Array, '/piwigo/>themes...', false)
#10 /usr/share/webapps/piwigo/include/template.class.php(1398): FileCombiner->combine()
#11 /usr/share/webapps/piwigo/include/template.class.php(517): CssLoader->get_css()
#12 /usr/share/webapps/piwigo/include/template.class.php(490): Template->flush()
#13 /usr/share/webapps/piwigo/index.php(354): Template->pparse('index') #14 {main} thrown in /usr/share/webapps/piwigo/_data/templates_c/ehk1dl^33cbd7b4ce204d3721f4e69415f71aee89e547bb_0.file.index.css.tpl.php on line 60
```

Any idea about what could be the cause? 

Thank you.

**Comment by bbbart** [comment]
I'm seeing the same error on my installation even after deleting all files in `_data/templates_c`.

**Comment by angel6700** [comment]
Are you using php8.
I think the problem could be related to that.

**Comment by bbbart** [comment]
you're right! moving to php7.4 solved all these errors at once.

thank you for the hint!

**Comment by plegall** [comment]
I close this issue, but it would be nice to test it again with the upcoming Piwigo 13. It should be compatible with PHP 8.
