### ISSUE TITLE
Can't view users

### ISSUE THREAD

**Issue by Trial-In-Error** [Piwigo/Piwigo#1589]
I just set up a brand-new, self-hosted Piwigo instance (this was shockingly hard, by the way!), and the Users table wasn't loading correctly in the admin interface. There was this error in the network tab:
```
Warning: [mysql error 1064] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups WHERE name LIKE '%%'' at line 1
SELECT id FROM groups WHERE name LIKE '%%'; in /data/www/default/photos/include/dblayer/functions_mysqli.inc.php on line 847
Fatal error: Uncaught Error: Call to a member function fetch_assoc() on bool in /data/www/default/photos/include/dblayer/functions_mysqli.inc.php:211 Stack trace: #0 /data/www/default/photos/include/ws_functions/pwg.users.php(49): pwg_db_fetch_assoc(false) #1 /data/www/default/photos/include/ws_core.inc.php(600): ws_users_getList(Array, Object(PwgServer)) #2 /data/www/default/photos/include/ws_protocols/rest_handler.php(41): PwgServer->invoke('pwg.users.getLi...', Array) #3 /data/www/default/photos/include/ws_core.inc.php(281): PwgRestRequestHandler->handleRequest(Object(PwgServer)) #4 /data/www/default/photos/ws.php(22): PwgServer->run() #5 {main} thrown in /data/www/default/photos/include/dblayer/functions_mysqli.inc.php on line 211
```

After following that stack trace to [this line](https://github.com/Piwigo/Piwigo/blob/master/include/ws_functions/pwg.users.php#L47), I fixed it by adding my database name to the query. Should Piwigo USE the database before calling this? Or is there some config I can add so mysqld always USEs the correct database?

**Comment by flop25** [comment]
Hello
check at the bottom what the issue really is:
https://github.com/Piwigo/Piwigo/wiki/Technical-changes-in-Piwigo-12
