### ISSUE TITLE
13.5.0 Permissions page error with PHP 8.1

### ISSUE THREAD

**Issue by skaldenhoven** [Piwigo/Piwigo#1863]
Upgraded to 13.5.0 and added some new albums today and when trying to set permissions the page threw an error. This was using PHP 8.1.
Switched back to PHP 7.2 which was also still on my server and the page worked without issue.
Verified whether the function.inc.php was the most recent one and even copied complete include directory from the installer zip over the current directory but with same result.
Below the error thrown.
`
Fatal error: Uncaught ValueError: Unknown format specifier "j" in /var/www/fotos/include/functions.inc.php:1218 Stack trace: #0 /var/www/fotos/include/functions.inc.php(1218): vsprintf() #1 /var/www/fotos/_data/templates_c/p6jhns^a274768b87497ffd55d466b1fbc581c81f970752_0.file.cat_perm.tpl.php(159): l10n() #2 /var/www/fotos/include/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_63cffb55d35d71_47390677() #3 /var/www/fotos/include/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode() #4 /var/www/fotos/include/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render() #5 /var/www/fotos/include/smarty/libs/sysplugins/smarty_internal_templatebase.php(238): Smarty_Internal_Template->render() #6 /var/www/fotos/include/smarty/libs/sysplugins/smarty_internal_templatebase.php(116): Smarty_Internal_TemplateBase->_execute() #7 /var/www/fotos/include/template.class.php(469): Smarty_Internal_TemplateBase->fetch() #8 /var/www/fotos/include/template.class.php(392): Template->parse() #9 /var/www/fotos/admin/cat_perm.php(297): Template->assign_var_from_handle() #10 /var/www/fotos/admin/album.php(73): include('...') #11 /var/www/fotos/admin.php(345): include('...') #12 {main} thrown in /var/www/fotos/include/functions.inc.php on line 1218
`

System info

Piwigo 13.5.0
Besturingssysteem: Linux
PHP: 8.1.15 (Toon info) [2023-02-07 16:09:56]
MySQL: 8.0.30-22 [2023-02-07 16:09:56]
Afbeeldingen-bibliotheek: ImageMagick 6.9.11-60

Also switched some of the themes but to no avail.
Anything other or just something that needs to be updated?
If more info is needed let me know.

**Comment by skaldenhoven** [comment]
Seems to be fixed now since the update to 13.7.0
