### ISSUE TITLE
Databse-Querry-Error

### ISSUE THREAD

**Issue by pegelow** [Piwigo/Piwigo#1892]
When I edit an album and click the checkbox for "Apply settings for sub-albums", I get:

Fatal error: Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'OR uppercats REGEXP '(^|,)23(,|$)'' at line 4 in /var/www/html/piwigo/include/dblayer/functions_mysqli.inc.php:132 Stack trace: #0 /var/www/html/piwigo/include/dblayer/functions_mysqli.inc.php(132): mysqli->query() #1 /var/www/html/piwigo/include/dblayer/functions_mysqli.inc.php(888): pwg_query() #2 /var/www/html/piwigo/include/functions_category.inc.php(323): query2array() #3 /var/www/html/piwigo/admin/cat_modify.php(122): get_subcat_ids() #4 /var/www/html/piwigo/admin/album.php(64): include('...') #5 /var/www/html/piwigo/admin.php(345): include('...') #6 {main} thrown in /var/www/html/piwigo/include/dblayer/functions_mysqli.inc.php on line 132

**Comment by pegelow** [comment]
![screenshot_21](https://user-images.githubusercontent.com/4677678/227999557-d0fc4c86-1039-4aa5-9ea3-f12157b49f85.png)

**Comment by klaoun** [comment]
hi
it is version piwigo 13.6.0 but have you test version master ?
thanks
![la](https://user-images.githubusercontent.com/36087587/228015086-c4a88e2c-fc05-4815-b04e-60252a0a8e41.jpg)
