### ISSUE TITLE
Fatal error: Uncaught DivisionByZeroError

### ISSUE THREAD

**Issue by zhcosin** [Piwigo/Piwigo#2181]
Hi, the following error has occur when I click my username(admin) at the top right corner in the piwigo page:
```
Fatal error: Uncaught DivisionByZeroError: Division by zero in /config/www/_data/templates_c/p6jhns^97fe272ea0e342f147a8d8650c738e329e4c10f1_0.file.intro.tpl.php:504
Stack trace:
#0 /app/www/public/include/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_667533c8cb4a47_52699291()
#1 /app/www/public/include/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode()
#2 /app/www/public/include/smarty/libs/sysplugins/smarty_internal_template.php(217): Smarty_Template_Compiled->render()
#3 /app/www/public/include/smarty/libs/sysplugins/smarty_internal_templatebase.php(238): Smarty_Internal_Template->render()
#4 /app/www/public/include/smarty/libs/sysplugins/smarty_internal_templatebase.php(116): Smarty_Internal_TemplateBase->_execute()
#5 /app/www/public/include/template.class.php(483): Smarty_Internal_TemplateBase->fetch()
#6 /app/www/public/include/template.class.php(406): Template->parse()
#7 /app/www/public/admin/intro.php(497): Template->assign_var_from_handle()
#8 /app/www/public/admin.php(346): include('...')
#9 {main} thrown in /config/www/_data/templates_c/p6jhns^97fe272ea0e342f147a8d8650c738e329e4c10f1_0.file.intro.tpl.php on line 504

```
before this, I modify the configure file show as following to solve chinese fold name problem:
```
$conf['sync_chars_regex'] = '/^[\x{2e80}-\x{fe4f}a-zA-Z0-9-_.\(\)\[\]\!@#×\s]+$/u';
```
but when I restore this configure and restart the container, the error remains.
My piwigo deploy by docker with image linuxserver/piwigo:latest which use 14.4.0 version of this repository. Is anyone some help?

**Comment by zhcosin** [comment]
参考 [[resolved] Cannot view admin after first synchronization. Getting an error](https://piwigo.org/forum/viewtopic.php?pid=188544#p188544)  给出的清理缓存的方法解决了。深表感谢。
