### ISSUE TITLE
Bug Prelod Plugin

### ISSUE THREAD

**Issue by zorodimanche** [Piwigo/Piwigo#677]
Notice: Undefined variable: thisSize in /home/u843758261/public_html/plugins/Preload/main.inc.php on line 197

Fatal error: Uncaught TypeError: Argument 2 passed to DerivativeImage::__construct() must be an instance of SrcImage, string given, called in /home/u843758261/public_html/plugins/Preload/main.inc.php on line 197 and defined in /home/u843758261/public_html/include/derivative.inc.php:194 Stack trace: #0 /home/u843758261/public_html/plugins/Preload/main.inc.php(197): DerivativeImage->__construct(NULL, 'medium') #1 /home/u843758261/public_html/include/functions_plugins.inc.php(279): Preload_populate_images() #2 /home/u843758261/public_html/include/page_header.php(29): trigger_notify('loc_begin_page_...') #3 /home/u843758261/public_html/picture.php(1035): include('/home/u84375826...') #4 {main} thrown in /home/u843758261/public_html/include/derivative.inc.php on line 194

**Comment by heviiguy** [comment]
No comments, let alone a resolution, yet??

**Comment by jambrosino** [comment]
I had the same problem. I'm not sure if this is a fix or a workaround :), but install the Automatic Size plugin. The error goes away.

**Comment by heviiguy** [comment]
Thanks for the tip, jambrosino. I worked around the issue by getting rid of the Preload Module.
